<a href="https://colab.research.google.com/github/learneverythingai/Shivam-Modi-Data-Science-Analytics-Course/blob/main/Deep%20Learning%20Course/LSTM_for_NLP_Old.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Author and Instructor of this Notebook is **Shivam Modi**.

## LinkedIn: https://www.linkedin.com/in/shivam-modi-datascientist/

# Long-short term memory
Long-Short Term Memory networks or LSTMs are a variant of RNN that solve the Long term memory problem. LSTM is also an artificial recurrent neural network architecture used in the field of deep learning. Unlike standard feedforward neural networks, LSTM has feedback connections. It can not only process single data points, but also entire sequences of data.

# Fake News Classification using Long-short term memory
[Dataset](https://www.kaggle.com/c/fake-news/data#)

In [ ]:
#importing necessary library
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing import text

In [ ]:
#loading the dataset
df=pd.read_csv('/content/train.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
#Drop Nan Values
df=df.dropna()

In [ ]:
#Get the Independent Features
X=df.drop('label',axis=1)

In [ ]:
#Get the Dependent features
y=df['label']

In [ ]:
#checking out the x shape
X.shape

(18285, 4)

In [ ]:
#also checking the y shape
y.shape

(18285,)

In [ ]:
#Vocabulary size
voc_size=5000

In [ ]:
#defifning one shot representation
messages=X.copy()
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
#importing required library
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#Preprocessing dataset
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
#definfing oneshot representation
onehot_repr = [text.one_hot(word,voc_size) for word in corpus]
onehot_repr

[[4718, 1606, 108, 3536, 553, 2727, 4306, 2469, 1601, 3014],
 [4186, 982, 3908, 3140, 3797, 3542, 4952],
 [2512, 2970, 583, 1870],
 [4169, 4773, 1711, 3464, 4004, 3042],
 [3577, 3797, 4315, 45, 3138, 3466, 3797, 3331, 1213, 3495],
 [3824,
  3898,
  42,
  1814,
  1,
  1138,
  2217,
  2180,
  361,
  623,
  4609,
  143,
  1,
  3627,
  4952],
 [441, 3278, 872, 4495, 2612, 407, 410, 1549, 4992, 4840, 2939],
 [3957, 4707, 714, 3342, 2007, 2120, 1138, 4763, 4992, 4840, 2939],
 [4669, 2779, 3928, 1895, 2985, 3637, 1017, 856, 1138, 3455],
 [3747, 3874, 2601, 133, 1892, 3295, 3759, 4078],
 [3824, 1734, 818, 3801, 764, 228, 2500, 695, 130, 1287, 3464],
 [3464, 3021, 553, 3637, 1138, 2007],
 [899, 155, 3951, 3209, 1927, 306, 2863, 2573, 186],
 [2045, 47, 4942, 33, 2410, 4819, 801, 4992, 4840, 2939],
 [784, 2919, 154, 172, 1809, 4992, 4840, 2939],
 [3118, 2203, 2867, 889, 840, 2118, 885, 3679, 2250, 4257],
 [1830, 2864, 982],
 [4121, 61, 882, 4616, 1138, 4192, 3973, 4952],
 [831, 256, 3908, 78, 569

In [ ]:

#Embedding Representation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2469 1601 3014]
 [   0    0    0 ... 3797 3542 4952]
 [   0    0    0 ... 2970  583 1870]
 ...
 [   0    0    0 ... 4992 4840 2939]
 [   0    0    0 ...  723  482 1596]
 [   0    0    0 ... 4064 1715 4067]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4718,
       1606,  108, 3536,  553, 2727, 4306, 2469, 1601, 3014], dtype=int32)

In [ ]:
# Defining model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
#storing the final output
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
#printing fianl x & y shape
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
#spliting the dataset into test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
#Model training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 10s 38ms/step - loss: 0.3367 - accuracy: 0.8423 - val_loss: 0.1927 - val_accuracy: 0.9148
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1391 - accuracy: 0.9453 - val_loss: 0.1948 - val_accuracy: 0.9220
Epoch 3/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0997 - accuracy: 0.9623 - val_loss: 0.2225 - val_accuracy: 0.9215
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0789 - accuracy: 0.9722 - val_loss: 0.2454 - val_accuracy: 0.9175
Epoch 5/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0487 - accuracy: 0.9837 - val_loss: 0.3086 - val_accuracy: 0.9109
Epoch 6/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0339 - accuracy: 0.9897 - val_loss: 0.3652 - val_accuracy: 0.9085
Epoch 7/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0210 - accuracy: 0.9934 - val_loss: 0.3907 - val_accuracy: 0.916

In [ ]:
#adding dropout
from tensorflow.keras.layers import Dropout
#Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
#performance matrix
y_pred=model.predict(X_test)
from sklearn.metrics import confusion_matrix

In [ ]:
#printing confusion matrix
confusion_matrix(y_test,y_pred.round())

array([[2779,  640],
       [ 870, 1746]])

In [ ]:
#printing the accuracyS
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred.round())

0.7497928748964374