<a href="https://colab.research.google.com/github/learneverythingai/Shivam-Modi-Data-Science-Analytics-Course/blob/main/Advanced%20Deep%20Learning%20Course/PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Author and Instructor of this Notebook is **Shivam Modi**.
## LinkedIn: https://www.linkedin.com/in/shivam-modi-datascientist/

In [ ]:
import torch
import numpy as np

In [ ]:
empty=torch.empty(3,5) #empty tensor
empty

tensor([[2.5223e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
random=torch.rand(2,2,2) # tensor with values 
random

tensor([[[0.7653, 0.1305],
         [0.4057, 0.4857]],

        [[0.4947, 0.2280],
         [0.8335, 0.8411]]])

In [ ]:
zeros=torch.zeros(2,3) #tensor of zeros
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(2, 3, 4)  # tensor ofones
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
ones.dtype #returns the data type
ones.shape #returns the shape of the tensor

torch.Size([2, 3, 4])

In [ ]:
array=[1,2,4,3,5]
t_tensor=torch.tensor(array,dtype=torch.int32) #tensor from python list
t_tensor.dtype

torch.int32

In [ ]:
x= torch.rand(2,2)
y= torch.rand(2,2)

# addition -element wise
z=x+y
print(z)
torch.add(x,y)

tensor([[0.8771, 1.3077],
        [0.6088, 1.1772]])


tensor([[0.8771, 1.3077],
        [0.6088, 1.1772]])

In [ ]:
# substaction

z=x-y
print(z)
torch.sub(x,y)

tensor([[0.7521, 0.6085],
        [0.2430, 0.5790]])


tensor([[0.7521, 0.6085],
        [0.2430, 0.5790]])

In [ ]:
# mul
print(x*y)
torch.mul(x,y)

tensor([[0.0509, 0.3349],
        [0.0779, 0.2627]])


tensor([[0.0509, 0.3349],
        [0.0779, 0.2627]])

In [ ]:
# div
print(x/y)
torch.div(x,y)

tensor([[13.0399,  2.7407],
        [ 2.3289,  2.9354]])


tensor([[13.0399,  2.7407],
        [ 2.3289,  2.9354]])

In [ ]:
# slicing
tensor=torch.rand(3,5,4)
print(tensor[:,4,:])

element=tensor[1,2,3]
element.item()

tensor([[0.2682, 0.1161, 0.3177, 0.0985],
        [0.6787, 0.9804, 0.1231, 0.0892],
        [0.5965, 0.9153, 0.1377, 0.9007]])


0.8659446239471436

In [ ]:
tensor.shape
tensor.view(-1,5)  #reshaping
tensor.view(5,3,4)

tensor([[[0.3037, 0.5589, 0.2555, 0.1433],
         [0.4878, 0.4412, 0.8057, 0.5773],
         [0.8398, 0.9128, 0.7940, 0.1228]],

        [[0.2837, 0.3292, 0.2130, 0.5809],
         [0.2682, 0.1161, 0.3177, 0.0985],
         [0.8333, 0.7391, 0.5300, 0.8072]],

        [[0.7496, 0.6627, 0.2572, 0.8755],
         [0.1714, 0.0340, 0.3006, 0.8659],
         [0.1447, 0.5138, 0.7010, 0.8082]],

        [[0.6787, 0.9804, 0.1231, 0.0892],
         [0.1534, 0.5025, 0.5299, 0.1883],
         [0.0425, 0.3837, 0.0097, 0.3896]],

        [[0.6749, 0.3242, 0.6580, 0.6785],
         [0.1563, 0.9209, 0.3689, 0.9923],
         [0.5965, 0.9153, 0.1377, 0.9007]]])

In [ ]:
np_array=tensor.numpy()
np_array  #numpy array

tensor_2=torch.from_numpy(np_array)
tensor_2 #torch tensor

tensor([[[0.3037, 0.5589, 0.2555, 0.1433],
         [0.4878, 0.4412, 0.8057, 0.5773],
         [0.8398, 0.9128, 0.7940, 0.1228],
         [0.2837, 0.3292, 0.2130, 0.5809],
         [0.2682, 0.1161, 0.3177, 0.0985]],

        [[0.8333, 0.7391, 0.5300, 0.8072],
         [0.7496, 0.6627, 0.2572, 0.8755],
         [0.1714, 0.0340, 0.3006, 0.8659],
         [0.1447, 0.5138, 0.7010, 0.8082],
         [0.6787, 0.9804, 0.1231, 0.0892]],

        [[0.1534, 0.5025, 0.5299, 0.1883],
         [0.0425, 0.3837, 0.0097, 0.3896],
         [0.6749, 0.3242, 0.6580, 0.6785],
         [0.1563, 0.9209, 0.3689, 0.9923],
         [0.5965, 0.9153, 0.1377, 0.9007]]])

In [ ]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    tensor=torch.tensor([1,2,3,4],dtype=torch.float32,device=device)
    tensor_2=([2,3,5])
    tensor_2=tensor_2.to(device)

False

In [ ]:
torch.randn(3,3,requires_grad=True)

In [ ]:
# important submodules in pytorch

torch
torch.nn
torch.optim
torch.optim.lr_scheduler


<module 'torch.optim.lr_scheduler' from '/Users/home2/.conda/envs/py38/lib/python3.8/site-packages/torch/optim/lr_scheduler.py'>